spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27017/talentlens?authSource=admin}
      database: ${MONGODB_DATABASE:talentlens}
      auto-index-creation: false

